import React, { useState, useCallback, useEffect } from 'react';
import LiveSession from './components/LiveSession';
import InfoCards from './components/InfoCards';
import Sidebar from './components/Sidebar';
import About from './components/About';
import Commissioners from './components/Commissioners';
import { TopicCard, ConnectionState, Commissioner, Post, ElectionConfig } from './types';
import { getSupabase } from './utils/supabaseClient';

const App: React.FC = () => {
  const [loading, setLoading] = useState(true);
  const [cards, setCards] = useState<TopicCard[]>([]);
  const [connectionState, setConnectionState] = useState<ConnectionState>(ConnectionState.DISCONNECTED);
  const [activeTab, setActiveTab] = useState<string>('session'); // Default to session view
  
  // Election Data State (Lifted up to share with AI)
  const [electionContext, setElectionContext] = useState<string>("");
  const [commissioners, setCommissioners] = useState<Commissioner[]>([]);
  const [posts, setPosts] = useState<Post[]>([]);
  const [config, setConfig] = useState<ElectionConfig | null>(null);

  // Handler for cards generated by Atlas or Echo
  const handleCardGenerated = useCallback((card: TopicCard) => {
    setCards(prev => [card, ...prev]);
  }, []);

  // Simulate App Loading / Splash Screen
  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 3500); // Extended slightly for the new animation
    return () => clearTimeout(timer);
  }, []);

  // Fetch data to provide context to AI
  useEffect(() => {
    const fetchData = async () => {
        const supabase = getSupabase();
        if (!supabase) return;

        // 1. Fetch Basic Entities
        const { data: candidates } = await supabase.from('candidates').select('id, name, position, like_count, manifesto');
        const { data: votes } = await supabase.from('votes').select('candidate_id, position');
        const { data: comms } = await supabase.from('commissioners').select('*').order('name');
        
        // 2. Fetch Deep Analysis Data (Posts, Comments, Config)
        const { data: postsData } = await supabase.from('posts').select('*').order('created_at', { ascending: false }).limit(15);
        const { data: commentsData } = await supabase.from('comments').select('content, author_name, post_id').order('created_at', { ascending: false }).limit(30);
        const { data: configData } = await supabase.from('election_config').select('*').single();

        if (comms) setCommissioners(comms);
        if (postsData) setPosts(postsData);
        if (configData) setConfig(configData);

        if (candidates && votes) {
            // A. Calculate Status Per Position (Winner vs Tie)
            const positionStats: Record<string, Record<string, number>> = {};
            candidates.forEach(c => {
                if (!positionStats[c.position]) positionStats[c.position] = {};
                positionStats[c.position][c.id] = 0;
            });
            votes.forEach(v => {
                if (positionStats[v.position] && positionStats[v.position][v.candidate_id] !== undefined) {
                    positionStats[v.position][v.candidate_id]++;
                }
            });

            const statusSummary = Object.keys(positionStats).map(pos => {
                const counts = Object.values(positionStats[pos]);
                const max = Math.max(...counts, 0);
                const isTie = counts.filter(c => c === max).length > 1;
                const totalForPos = counts.reduce((a,b) => a+b, 0);

                let status = "Waiting for votes";
                if (totalForPos > 0) {
                    status = isTie ? "TIE / TOO CLOSE TO CALL" : "WINNER PROJECTED";
                }
                return `Position: ${pos.toUpperCase()} -> Status: ${status}`;
            }).join('\n');

            // B. Format Manifestos
            const manifestoSummary = candidates.map(c => 
                `Candidate: ${c.name} (${c.position})\n   - Manifesto: "${c.manifesto}"`
            ).join('\n\n');

            // C. Format Commissioners
            const commissionerSummary = comms ? comms.map(c => 
                `- ${c.name} (${c.role})`
            ).join('\n') : "Loading...";

            // D. Format Community Pulse (Posts & Comments)
            let communityPulse = "No recent activity.";
            if (postsData && postsData.length > 0) {
                communityPulse = postsData.map(p => {
                    const relevantComments = commentsData?.filter(c => c.post_id === p.id).map(c => `   > ${c.author_name}: "${c.content}"`).join('\n') || "";
                    return `[${p.type.toUpperCase()}] ${p.author_name} (${p.author_role}): "${p.content}" (Likes: ${p.likes})${relevantComments ? '\n' + relevantComments : ''}`;
                }).join('\n\n');
            }

            // E. Format Election Config
            const configSummary = configData ? 
                `Organization: ${configData.org_name}\nEvent: ${configData.election_title}\nVoting Period: ${configData.start_date || 'TBA'} to ${configData.end_date || 'TBA'}` : 
                "Configuration not loaded.";
            
            // F. Visual Context for Echo
            const visualContext = `
VISUAL DASHBOARD DESCRIPTION (You are "seeing" this screen):
- The screen shows a "Data Center" dashboard.
- LEFT COLUMN: "Position Status" Board (Projected Winners/Ties).
- RIGHT COLUMN: "Candidates & Manifestos".
- CONTEXT: You also have access to the "Community Pulse" (Posts/Comments) for sentiment analysis.
            `;

            setElectionContext(`[REAL-TIME ELECTION FEED]

--- ELECTION CONFIGURATION ---
${configSummary}

--- POSITION STATUS (LIVE) ---
${statusSummary}

--- CANDIDATES ---
${manifestoSummary}

--- ELECTORAL BOARD ---
${commissionerSummary}

--- COMMUNITY PULSE (DEEP ANALYSIS) ---
${communityPulse}

${visualContext}`);
        }
    };
    
    // Initial fetch and poll
    fetchData();
    const interval = setInterval(fetchData, 4000);
    return () => clearInterval(interval);
  }, []);

  if (loading) {
    return (
      <div className="fixed inset-0 bg-[#000] z-[100] flex flex-col items-center justify-center overflow-hidden font-sans">
         <div className="relative flex flex-col items-center justify-center w-full max-w-2xl px-6">
            
            {/* Echo Speaking Animation (Visualizer) */}
            <div className="flex items-center justify-center gap-3 mb-10 h-24">
                {[...Array(5)].map((_, i) => (
                    <div key={i} className="w-4 md:w-5 bg-gradient-to-t from-blue-400 via-indigo-400 to-purple-400 rounded-full animate-pulse shadow-[0_0_15px_rgba(168,199,250,0.6)]" 
                         style={{ 
                             height: '100%', 
                             animationDuration: `${0.6 + i * 0.15}s`,
                             animationDelay: `${i * 0.05}s`,
                             animationDirection: 'alternate',
                             animationTimingFunction: 'ease-in-out'
                         }} 
                    />
                ))}
            </div>

            {/* Main Title */}
            <h1 className="text-7xl md:text-9xl font-black text-transparent bg-clip-text bg-gradient-to-br from-white via-blue-100 to-zinc-400 tracking-tighter animate-fade-in-up text-center mb-8 drop-shadow-2xl">
              Echo
            </h1>
            
            {/* Subtitle / Branding */}
            <div className="flex flex-col items-center gap-4 opacity-0 animate-fade-in-delayed">
               <span className="text-sm md:text-lg font-mono text-blue-200/80 uppercase tracking-[0.4em] font-medium">AI Campaign Assistant</span>
               
               <div className="flex items-center gap-3 px-6 py-3 rounded-full bg-white/5 border border-white/10 backdrop-blur-xl mt-6 shadow-2xl transform hover:scale-105 transition-transform duration-500">
                  <span className="text-xs md:text-sm text-zinc-400 tracking-wider">POWERED BY</span>
                  <div className="w-px h-4 bg-white/20"></div>
                  <div className="flex items-center gap-2">
                     <svg className="w-6 h-6 text-blue-400 animate-spin-slow" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z"/></svg>
                     <span className="text-lg md:text-xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-300 to-purple-300">Gemini 3.0</span>
                  </div>
               </div>
            </div>

         </div>
         <style>{`
            @keyframes fadeInUp {
                0% { opacity: 0; transform: translateY(40px) scale(0.95); }
                100% { opacity: 1; transform: translateY(0) scale(1); }
            }
            .animate-fade-in-up { animation: fadeInUp 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards; }
            .animate-fade-in-delayed { animation: fadeInUp 1.2s cubic-bezier(0.16, 1, 0.3, 1) 0.5s forwards; }
         `}</style>
      </div>
    );
  }

  return (
    <div className="flex flex-col md:flex-row h-[100dvh] w-full bg-google-bg overflow-hidden text-sm md:text-base font-sans animate-fade-in">
      
      {/* Sidebar / Bottom Nav */}
      <Sidebar activeTab={activeTab} onTabChange={setActiveTab} />

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col h-full relative overflow-hidden">
        
        {/* Mobile Header (Only visible on small screens) */}
        <div className="md:hidden flex items-center justify-between px-4 py-3 bg-google-bg border-b border-google-surfaceVariant z-20">
            <span className="font-semibold text-google-primary text-lg">Echo</span>
            <div className={`flex items-center gap-2 text-[10px] px-2 py-1 rounded-full ${connectionState === ConnectionState.CONNECTED ? 'bg-emerald-500/10 text-emerald-400' : 'bg-google-surfaceVariant text-zinc-400'}`}>
                <div className={`w-1.5 h-1.5 rounded-full ${connectionState === ConnectionState.CONNECTED ? 'bg-emerald-400 animate-pulse' : 'bg-zinc-500'}`} />
                {connectionState === ConnectionState.CONNECTED ? 'LIVE' : 'OFFLINE'}
            </div>
        </div>

        {/* Layout Container */}
        <div className="flex-1 relative h-full w-full overflow-hidden">
            
            {/* VIEW 1: Live Session (Echo) */}
            <div className={`absolute inset-0 transition-opacity duration-300 flex flex-col
                 ${activeTab === 'session' ? 'opacity-100 pointer-events-auto z-10' : 'opacity-0 pointer-events-none z-0'}
            `}>
                <div className="flex-1 p-4 md:p-6 flex flex-col h-full max-h-full">
                    <LiveSession 
                        onConnectionChange={setConnectionState}
                        onTranscription={() => {}} 
                        onCardGenerated={handleCardGenerated}
                        electionContext={electionContext}
                    />
                </div>
            </div>

            {/* VIEW 2: Analytics (Data Center) */}
            <div className={`absolute inset-0 bg-google-bg transition-transform duration-300 z-20
                ${activeTab === 'analytics' ? 'translate-x-0' : 'translate-x-full'}
            `}>
                <InfoCards 
                    cards={cards} 
                    activeTab={activeTab === 'analytics' ? 'analytics' : 'hidden'} 
                    electionContext={electionContext} 
                    commissioners={commissioners}
                    posts={posts}
                    config={config}
                />
            </div>

            {/* VIEW 3: Commissioners (Board) */}
            <div className={`absolute inset-0 bg-google-bg transition-transform duration-300 z-20
                ${activeTab === 'commissioners' ? 'translate-x-0' : 'translate-x-full'}
            `}>
                <Commissioners commissioners={commissioners} />
            </div>

            {/* VIEW 4: About / Guide */}
            <div className={`absolute inset-0 bg-google-bg transition-transform duration-300 z-20
                ${activeTab === 'about' ? 'translate-x-0' : 'translate-x-full'}
            `}>
                <About />
            </div>

        </div>
      </main>
    </div>
  );
};

export default App;